// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package db

import (
	"context"
)

const countAuditLog = `-- name: CountAuditLog :one
SELECT COUNT(*) FROM audit_log
WHERE tenant_id = $1
  AND ($2::text IS NULL OR user_id = $2)
  AND ($3::text IS NULL OR entity_type = $3)
  AND ($4::text IS NULL OR entity_id = $4)
`

type CountAuditLogParams struct {
	TenantID string `json:"tenant_id"`
	Column2  string `json:"column_2"`
	Column3  string `json:"column_3"`
	Column4  string `json:"column_4"`
}

func (q *Queries) CountAuditLog(ctx context.Context, arg CountAuditLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLog,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (id, tenant_id, user_id, user_name, action, entity_type, entity_id, entity_name, before, after, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertAuditLogParams struct {
	ID         string  `json:"id"`
	TenantID   string  `json:"tenant_id"`
	UserID     string  `json:"user_id"`
	UserName   string  `json:"user_name"`
	Action     string  `json:"action"`
	EntityType string  `json:"entity_type"`
	EntityID   string  `json:"entity_id"`
	EntityName *string `json:"entity_name"`
	Before     []byte  `json:"before"`
	After      []byte  `json:"after"`
	Ip         *string `json:"ip"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.UserName,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.EntityName,
		arg.Before,
		arg.After,
		arg.Ip,
	)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, tenant_id, user_id, user_name, action, entity_type, entity_id, entity_name, before, after, ip, created_at FROM audit_log
WHERE tenant_id = $1
  AND ($2::text IS NULL OR user_id = $2)
  AND ($3::text IS NULL OR entity_type = $3)
  AND ($4::text IS NULL OR entity_id = $4)
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListAuditLogParams struct {
	TenantID string `json:"tenant_id"`
	Column2  string `json:"column_2"`
	Column3  string `json:"column_3"`
	Column4  string `json:"column_4"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.UserName,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.EntityName,
			&i.Before,
			&i.After,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
