// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaign_reports.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertCampaignAIReport = `-- name: InsertCampaignAIReport :one
INSERT INTO campaign_ai_reports (id, tenant_id, campaign_id, report_type, content, period_start, period_end, generated_by, model)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, campaign_id, report_type, content, period_start, period_end, generated_at, generated_by, model
`

type InsertCampaignAIReportParams struct {
	ID          pgtype.UUID `json:"id"`
	TenantID    string      `json:"tenant_id"`
	CampaignID  string      `json:"campaign_id"`
	ReportType  string      `json:"report_type"`
	Content     string      `json:"content"`
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
	GeneratedBy *string     `json:"generated_by"`
	Model       *string     `json:"model"`
}

func (q *Queries) InsertCampaignAIReport(ctx context.Context, arg InsertCampaignAIReportParams) (CampaignAiReport, error) {
	row := q.db.QueryRow(ctx, insertCampaignAIReport,
		arg.ID,
		arg.TenantID,
		arg.CampaignID,
		arg.ReportType,
		arg.Content,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.GeneratedBy,
		arg.Model,
	)
	var i CampaignAiReport
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CampaignID,
		&i.ReportType,
		&i.Content,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.GeneratedAt,
		&i.GeneratedBy,
		&i.Model,
	)
	return i, err
}

const listCampaignAIReports = `-- name: ListCampaignAIReports :many
SELECT r.id, r.tenant_id, r.campaign_id, r.report_type, r.content,
       r.period_start, r.period_end, r.generated_at, r.model,
       u.name AS generated_by_name
FROM campaign_ai_reports r
LEFT JOIN users u ON r.generated_by = u.id
WHERE r.tenant_id = $1 AND r.campaign_id = $2 AND r.report_type = $3
ORDER BY r.generated_at DESC
LIMIT $4
`

type ListCampaignAIReportsParams struct {
	TenantID   string `json:"tenant_id"`
	CampaignID string `json:"campaign_id"`
	ReportType string `json:"report_type"`
	Limit      int32  `json:"limit"`
}

type ListCampaignAIReportsRow struct {
	ID              pgtype.UUID `json:"id"`
	TenantID        string      `json:"tenant_id"`
	CampaignID      string      `json:"campaign_id"`
	ReportType      string      `json:"report_type"`
	Content         string      `json:"content"`
	PeriodStart     pgtype.Date `json:"period_start"`
	PeriodEnd       pgtype.Date `json:"period_end"`
	GeneratedAt     time.Time   `json:"generated_at"`
	Model           *string     `json:"model"`
	GeneratedByName *string     `json:"generated_by_name"`
}

func (q *Queries) ListCampaignAIReports(ctx context.Context, arg ListCampaignAIReportsParams) ([]ListCampaignAIReportsRow, error) {
	rows, err := q.db.Query(ctx, listCampaignAIReports,
		arg.TenantID,
		arg.CampaignID,
		arg.ReportType,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignAIReportsRow
	for rows.Next() {
		var i ListCampaignAIReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CampaignID,
			&i.ReportType,
			&i.Content,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.GeneratedAt,
			&i.Model,
			&i.GeneratedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
