// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connector_resources.sql

package db

import (
	"context"
	"encoding/json"
)

const deleteConnectorResource = `-- name: DeleteConnectorResource :exec
DELETE FROM connector_resources WHERE id = $1
`

func (q *Queries) DeleteConnectorResource(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteConnectorResource, id)
	return err
}

const deleteConnectorResourcesByTenantProvider = `-- name: DeleteConnectorResourcesByTenantProvider :exec
DELETE FROM connector_resources WHERE tenant_id = $1 AND provider = $2
`

type DeleteConnectorResourcesByTenantProviderParams struct {
	TenantID string `json:"tenant_id"`
	Provider string `json:"provider"`
}

func (q *Queries) DeleteConnectorResourcesByTenantProvider(ctx context.Context, arg DeleteConnectorResourcesByTenantProviderParams) error {
	_, err := q.db.Exec(ctx, deleteConnectorResourcesByTenantProvider, arg.TenantID, arg.Provider)
	return err
}

const getConnectorResourceByID = `-- name: GetConnectorResourceByID :one
SELECT id, tenant_id, integration_id, provider, resource_type, resource_id, resource_name, metadata, created_at, updated_at FROM connector_resources WHERE id = $1 LIMIT 1
`

func (q *Queries) GetConnectorResourceByID(ctx context.Context, id string) (ConnectorResource, error) {
	row := q.db.QueryRow(ctx, getConnectorResourceByID, id)
	var i ConnectorResource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IntegrationID,
		&i.Provider,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceName,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorResourceForTenant = `-- name: GetConnectorResourceForTenant :one
SELECT id, tenant_id, integration_id, provider, resource_type, resource_id, resource_name, metadata, created_at, updated_at FROM connector_resources
WHERE tenant_id = $1 AND provider = $2 AND resource_type = $3 AND resource_id = $4
LIMIT 1
`

type GetConnectorResourceForTenantParams struct {
	TenantID     string `json:"tenant_id"`
	Provider     string `json:"provider"`
	ResourceType string `json:"resource_type"`
	ResourceID   string `json:"resource_id"`
}

func (q *Queries) GetConnectorResourceForTenant(ctx context.Context, arg GetConnectorResourceForTenantParams) (ConnectorResource, error) {
	row := q.db.QueryRow(ctx, getConnectorResourceForTenant,
		arg.TenantID,
		arg.Provider,
		arg.ResourceType,
		arg.ResourceID,
	)
	var i ConnectorResource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IntegrationID,
		&i.Provider,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceName,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnectorResources = `-- name: ListConnectorResources :many
SELECT id, tenant_id, integration_id, provider, resource_type, resource_id, resource_name, metadata, created_at, updated_at FROM connector_resources
WHERE tenant_id = $1 AND provider = $2 AND resource_type = $3
ORDER BY created_at DESC
`

type ListConnectorResourcesParams struct {
	TenantID     string `json:"tenant_id"`
	Provider     string `json:"provider"`
	ResourceType string `json:"resource_type"`
}

func (q *Queries) ListConnectorResources(ctx context.Context, arg ListConnectorResourcesParams) ([]ConnectorResource, error) {
	rows, err := q.db.Query(ctx, listConnectorResources, arg.TenantID, arg.Provider, arg.ResourceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConnectorResource
	for rows.Next() {
		var i ConnectorResource
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.IntegrationID,
			&i.Provider,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResourceName,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConnectorResource = `-- name: UpsertConnectorResource :exec
INSERT INTO connector_resources (
    id, tenant_id, integration_id, provider, resource_type, resource_id, resource_name, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (tenant_id, integration_id, resource_type, resource_id)
DO UPDATE SET
    resource_name = EXCLUDED.resource_name,
    metadata = EXCLUDED.metadata,
    updated_at = NOW()
`

type UpsertConnectorResourceParams struct {
	ID            string          `json:"id"`
	TenantID      string          `json:"tenant_id"`
	IntegrationID string          `json:"integration_id"`
	Provider      string          `json:"provider"`
	ResourceType  string          `json:"resource_type"`
	ResourceID    string          `json:"resource_id"`
	ResourceName  *string         `json:"resource_name"`
	Metadata      json.RawMessage `json:"metadata"`
}

func (q *Queries) UpsertConnectorResource(ctx context.Context, arg UpsertConnectorResourceParams) error {
	_, err := q.db.Exec(ctx, upsertConnectorResource,
		arg.ID,
		arg.TenantID,
		arg.IntegrationID,
		arg.Provider,
		arg.ResourceType,
		arg.ResourceID,
		arg.ResourceName,
		arg.Metadata,
	)
	return err
}
