// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: legal.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const createLegalTermVersion = `-- name: CreateLegalTermVersion :exec
INSERT INTO legal_term_versions (id, version, fallback_locale, translations, effective_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateLegalTermVersionParams struct {
	ID             string          `json:"id"`
	Version        int32           `json:"version"`
	FallbackLocale string          `json:"fallback_locale"`
	Translations   json.RawMessage `json:"translations"`
	EffectiveAt    time.Time       `json:"effective_at"`
	CreatedBy      *string         `json:"created_by"`
}

func (q *Queries) CreateLegalTermVersion(ctx context.Context, arg CreateLegalTermVersionParams) error {
	_, err := q.db.Exec(ctx, createLegalTermVersion,
		arg.ID,
		arg.Version,
		arg.FallbackLocale,
		arg.Translations,
		arg.EffectiveAt,
		arg.CreatedBy,
	)
	return err
}

const getLatestLegalTermVersion = `-- name: GetLatestLegalTermVersion :one
SELECT id, version, fallback_locale, translations, effective_at, created_by, created_at
FROM legal_term_versions
WHERE effective_at <= NOW()
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLatestLegalTermVersion(ctx context.Context) (LegalTermVersion, error) {
	row := q.db.QueryRow(ctx, getLatestLegalTermVersion)
	var i LegalTermVersion
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.FallbackLocale,
		&i.Translations,
		&i.EffectiveAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getLegalTermVersionByID = `-- name: GetLegalTermVersionByID :one
SELECT id, version, fallback_locale, translations, effective_at, created_by, created_at
FROM legal_term_versions
WHERE id = $1
`

func (q *Queries) GetLegalTermVersionByID(ctx context.Context, id string) (LegalTermVersion, error) {
	row := q.db.QueryRow(ctx, getLegalTermVersionByID, id)
	var i LegalTermVersion
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.FallbackLocale,
		&i.Translations,
		&i.EffectiveAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getMaxLegalTermVersion = `-- name: GetMaxLegalTermVersion :one
SELECT COALESCE(MAX(version), 0) AS max_version FROM legal_term_versions
`

func (q *Queries) GetMaxLegalTermVersion(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, getMaxLegalTermVersion)
	var max_version interface{}
	err := row.Scan(&max_version)
	return max_version, err
}

const hasUserAcceptedLegalVersion = `-- name: HasUserAcceptedLegalVersion :one
SELECT EXISTS (
    SELECT 1 FROM user_legal_acceptances
    WHERE user_id = $1 AND version_id = $2
) AS accepted
`

type HasUserAcceptedLegalVersionParams struct {
	UserID    string `json:"user_id"`
	VersionID string `json:"version_id"`
}

func (q *Queries) HasUserAcceptedLegalVersion(ctx context.Context, arg HasUserAcceptedLegalVersionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserAcceptedLegalVersion, arg.UserID, arg.VersionID)
	var accepted bool
	err := row.Scan(&accepted)
	return accepted, err
}

const listLegalTermVersions = `-- name: ListLegalTermVersions :many
SELECT id, version, fallback_locale, translations, effective_at, created_by, created_at
FROM legal_term_versions
ORDER BY version DESC
`

func (q *Queries) ListLegalTermVersions(ctx context.Context) ([]LegalTermVersion, error) {
	rows, err := q.db.Query(ctx, listLegalTermVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LegalTermVersion
	for rows.Next() {
		var i LegalTermVersion
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.FallbackLocale,
			&i.Translations,
			&i.EffectiveAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordLegalAcceptance = `-- name: RecordLegalAcceptance :exec
INSERT INTO user_legal_acceptances (user_id, version_id, locale_seen, ip)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, version_id) DO NOTHING
`

type RecordLegalAcceptanceParams struct {
	UserID     string  `json:"user_id"`
	VersionID  string  `json:"version_id"`
	LocaleSeen *string `json:"locale_seen"`
	Ip         *string `json:"ip"`
}

func (q *Queries) RecordLegalAcceptance(ctx context.Context, arg RecordLegalAcceptanceParams) error {
	_, err := q.db.Exec(ctx, recordLegalAcceptance,
		arg.UserID,
		arg.VersionID,
		arg.LocaleSeen,
		arg.Ip,
	)
	return err
}

const updateLegalTermVersion = `-- name: UpdateLegalTermVersion :exec
UPDATE legal_term_versions
SET fallback_locale = $2, translations = $3, effective_at = $4
WHERE id = $1
`

type UpdateLegalTermVersionParams struct {
	ID             string          `json:"id"`
	FallbackLocale string          `json:"fallback_locale"`
	Translations   json.RawMessage `json:"translations"`
	EffectiveAt    time.Time       `json:"effective_at"`
}

func (q *Queries) UpdateLegalTermVersion(ctx context.Context, arg UpdateLegalTermVersionParams) error {
	_, err := q.db.Exec(ctx, updateLegalTermVersion,
		arg.ID,
		arg.FallbackLocale,
		arg.Translations,
		arg.EffectiveAt,
	)
	return err
}
