// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_api_keys.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMcpApiKeyByHash = `-- name: GetMcpApiKeyByHash :one
SELECT id, tenant_id, name, key_prefix, key_hash, role, created_by, last_used_at, expires_at, revoked_at, created_at FROM mcp_api_keys
WHERE key_hash = $1 AND revoked_at IS NULL
LIMIT 1
`

func (q *Queries) GetMcpApiKeyByHash(ctx context.Context, keyHash string) (McpApiKey, error) {
	row := q.db.QueryRow(ctx, getMcpApiKeyByHash, keyHash)
	var i McpApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Role,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMcpApiKeyByIDAndTenant = `-- name: GetMcpApiKeyByIDAndTenant :one
SELECT id, tenant_id, name, key_prefix, key_hash, role, created_by, last_used_at, expires_at, revoked_at, created_at FROM mcp_api_keys
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetMcpApiKeyByIDAndTenantParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetMcpApiKeyByIDAndTenant(ctx context.Context, arg GetMcpApiKeyByIDAndTenantParams) (McpApiKey, error) {
	row := q.db.QueryRow(ctx, getMcpApiKeyByIDAndTenant, arg.ID, arg.TenantID)
	var i McpApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Role,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertMcpApiKey = `-- name: InsertMcpApiKey :one
INSERT INTO mcp_api_keys (
    id, tenant_id, name, key_prefix, key_hash, role, created_by, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, name, key_prefix, key_hash, role, created_by, last_used_at, expires_at, revoked_at, created_at
`

type InsertMcpApiKeyParams struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Name      string             `json:"name"`
	KeyPrefix string             `json:"key_prefix"`
	KeyHash   string             `json:"key_hash"`
	Role      string             `json:"role"`
	CreatedBy *string            `json:"created_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertMcpApiKey(ctx context.Context, arg InsertMcpApiKeyParams) (McpApiKey, error) {
	row := q.db.QueryRow(ctx, insertMcpApiKey,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.Role,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i McpApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Role,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listMcpApiKeysByTenant = `-- name: ListMcpApiKeysByTenant :many
SELECT id, tenant_id, name, key_prefix, role, created_by, last_used_at, expires_at, revoked_at, created_at
FROM mcp_api_keys
WHERE tenant_id = $1
ORDER BY created_at DESC
`

type ListMcpApiKeysByTenantRow struct {
	ID         string             `json:"id"`
	TenantID   string             `json:"tenant_id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	Role       string             `json:"role"`
	CreatedBy  *string            `json:"created_by"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

func (q *Queries) ListMcpApiKeysByTenant(ctx context.Context, tenantID string) ([]ListMcpApiKeysByTenantRow, error) {
	rows, err := q.db.Query(ctx, listMcpApiKeysByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMcpApiKeysByTenantRow
	for rows.Next() {
		var i ListMcpApiKeysByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.KeyPrefix,
			&i.Role,
			&i.CreatedBy,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeMcpApiKey = `-- name: RevokeMcpApiKey :exec
UPDATE mcp_api_keys
SET revoked_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND revoked_at IS NULL
`

type RevokeMcpApiKeyParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) RevokeMcpApiKey(ctx context.Context, arg RevokeMcpApiKeyParams) error {
	_, err := q.db.Exec(ctx, revokeMcpApiKey, arg.ID, arg.TenantID)
	return err
}

const updateMcpApiKeyLastUsed = `-- name: UpdateMcpApiKeyLastUsed :exec
UPDATE mcp_api_keys
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateMcpApiKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateMcpApiKeyLastUsed, id)
	return err
}
