// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_adjustments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approvePendingAdjustment = `-- name: ApprovePendingAdjustment :exec
UPDATE pending_adjustments
SET status = 'approved', resolved_at = NOW(), resolved_by = $2
WHERE id = $1
`

type ApprovePendingAdjustmentParams struct {
	ID         string  `json:"id"`
	ResolvedBy *string `json:"resolved_by"`
}

func (q *Queries) ApprovePendingAdjustment(ctx context.Context, arg ApprovePendingAdjustmentParams) error {
	_, err := q.db.Exec(ctx, approvePendingAdjustment, arg.ID, arg.ResolvedBy)
	return err
}

const expireOldPendingAdjustments = `-- name: ExpireOldPendingAdjustments :execrows
UPDATE pending_adjustments
SET status = 'expired'
WHERE status = 'pending' AND expires_at IS NOT NULL AND expires_at < NOW()
`

func (q *Queries) ExpireOldPendingAdjustments(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireOldPendingAdjustments)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPendingAdjustmentByID = `-- name: GetPendingAdjustmentByID :one
SELECT id, tenant_id, campaign_resource_id, adjustment_type, current_value, proposed_value, reason, status, expires_at, resolved_at, resolved_by, created_at FROM pending_adjustments WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPendingAdjustmentByID(ctx context.Context, id string) (PendingAdjustment, error) {
	row := q.db.QueryRow(ctx, getPendingAdjustmentByID, id)
	var i PendingAdjustment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CampaignResourceID,
		&i.AdjustmentType,
		&i.CurrentValue,
		&i.ProposedValue,
		&i.Reason,
		&i.Status,
		&i.ExpiresAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertPendingAdjustment = `-- name: InsertPendingAdjustment :one
INSERT INTO pending_adjustments (
    id, tenant_id, campaign_resource_id, adjustment_type,
    current_value, proposed_value, reason, status, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending', $8)
RETURNING id, tenant_id, campaign_resource_id, adjustment_type, current_value, proposed_value, reason, status, expires_at, resolved_at, resolved_by, created_at
`

type InsertPendingAdjustmentParams struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	CampaignResourceID string             `json:"campaign_resource_id"`
	AdjustmentType     string             `json:"adjustment_type"`
	CurrentValue       float64            `json:"current_value"`
	ProposedValue      float64            `json:"proposed_value"`
	Reason             string             `json:"reason"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertPendingAdjustment(ctx context.Context, arg InsertPendingAdjustmentParams) (PendingAdjustment, error) {
	row := q.db.QueryRow(ctx, insertPendingAdjustment,
		arg.ID,
		arg.TenantID,
		arg.CampaignResourceID,
		arg.AdjustmentType,
		arg.CurrentValue,
		arg.ProposedValue,
		arg.Reason,
		arg.ExpiresAt,
	)
	var i PendingAdjustment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CampaignResourceID,
		&i.AdjustmentType,
		&i.CurrentValue,
		&i.ProposedValue,
		&i.Reason,
		&i.Status,
		&i.ExpiresAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingAdjustmentsByTenant = `-- name: ListPendingAdjustmentsByTenant :many
SELECT id, tenant_id, campaign_resource_id, adjustment_type, current_value, proposed_value, reason, status, expires_at, resolved_at, resolved_by, created_at FROM pending_adjustments
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPendingAdjustmentsByTenant(ctx context.Context, tenantID string) ([]PendingAdjustment, error) {
	rows, err := q.db.Query(ctx, listPendingAdjustmentsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingAdjustment
	for rows.Next() {
		var i PendingAdjustment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CampaignResourceID,
			&i.AdjustmentType,
			&i.CurrentValue,
			&i.ProposedValue,
			&i.Reason,
			&i.Status,
			&i.ExpiresAt,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAdjustmentsByTenantAndStatus = `-- name: ListPendingAdjustmentsByTenantAndStatus :many
SELECT id, tenant_id, campaign_resource_id, adjustment_type, current_value, proposed_value, reason, status, expires_at, resolved_at, resolved_by, created_at FROM pending_adjustments
WHERE tenant_id = $1 AND status = $2
ORDER BY created_at DESC
`

type ListPendingAdjustmentsByTenantAndStatusParams struct {
	TenantID string `json:"tenant_id"`
	Status   string `json:"status"`
}

func (q *Queries) ListPendingAdjustmentsByTenantAndStatus(ctx context.Context, arg ListPendingAdjustmentsByTenantAndStatusParams) ([]PendingAdjustment, error) {
	rows, err := q.db.Query(ctx, listPendingAdjustmentsByTenantAndStatus, arg.TenantID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingAdjustment
	for rows.Next() {
		var i PendingAdjustment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CampaignResourceID,
			&i.AdjustmentType,
			&i.CurrentValue,
			&i.ProposedValue,
			&i.Reason,
			&i.Status,
			&i.ExpiresAt,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectPendingAdjustment = `-- name: RejectPendingAdjustment :exec
UPDATE pending_adjustments
SET status = 'rejected', resolved_at = NOW(), resolved_by = $2
WHERE id = $1
`

type RejectPendingAdjustmentParams struct {
	ID         string  `json:"id"`
	ResolvedBy *string `json:"resolved_by"`
}

func (q *Queries) RejectPendingAdjustment(ctx context.Context, arg RejectPendingAdjustmentParams) error {
	_, err := q.db.Exec(ctx, rejectPendingAdjustment, arg.ID, arg.ResolvedBy)
	return err
}
