// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_insights.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPendingInsightSync = `-- name: ListPendingInsightSync :many
SELECT ppr.id, ppr.post_id, ppr.platform, ppr.provider, ppr.external_id, ppr.status, ppr.error_message, ppr.published_at, ppr.created_at, p.tenant_id AS post_tenant_id
FROM post_publish_results ppr
JOIN posts p ON p.id = ppr.post_id
LEFT JOIN post_insights pi ON pi.publish_result_id = ppr.id AND pi.insight_window = $1
WHERE ppr.status = 'published'
  AND ppr.published_at >= $2
  AND ppr.published_at <  $3
  AND pi.id IS NULL
`

type ListPendingInsightSyncParams struct {
	InsightWindow string             `json:"insight_window"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	PublishedAt_2 pgtype.Timestamptz `json:"published_at_2"`
}

type ListPendingInsightSyncRow struct {
	ID           string             `json:"id"`
	PostID       string             `json:"post_id"`
	Platform     string             `json:"platform"`
	Provider     string             `json:"provider"`
	ExternalID   *string            `json:"external_id"`
	Status       string             `json:"status"`
	ErrorMessage *string            `json:"error_message"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	CreatedAt    time.Time          `json:"created_at"`
	PostTenantID string             `json:"post_tenant_id"`
}

func (q *Queries) ListPendingInsightSync(ctx context.Context, arg ListPendingInsightSyncParams) ([]ListPendingInsightSyncRow, error) {
	rows, err := q.db.Query(ctx, listPendingInsightSync, arg.InsightWindow, arg.PublishedAt, arg.PublishedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingInsightSyncRow
	for rows.Next() {
		var i ListPendingInsightSyncRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Platform,
			&i.Provider,
			&i.ExternalID,
			&i.Status,
			&i.ErrorMessage,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.PostTenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostInsightsByPostID = `-- name: ListPostInsightsByPostID :many
SELECT id, publish_result_id, post_id, platform, insight_window, metrics, raw_response, synced_at FROM post_insights
WHERE post_id = $1
ORDER BY synced_at DESC
`

func (q *Queries) ListPostInsightsByPostID(ctx context.Context, postID string) ([]PostInsight, error) {
	rows, err := q.db.Query(ctx, listPostInsightsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostInsight
	for rows.Next() {
		var i PostInsight
		if err := rows.Scan(
			&i.ID,
			&i.PublishResultID,
			&i.PostID,
			&i.Platform,
			&i.InsightWindow,
			&i.Metrics,
			&i.RawResponse,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPostInsight = `-- name: UpsertPostInsight :exec
INSERT INTO post_insights (id, publish_result_id, post_id, platform, insight_window, metrics, raw_response, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
ON CONFLICT (publish_result_id, insight_window) DO UPDATE
  SET metrics      = EXCLUDED.metrics,
      raw_response = EXCLUDED.raw_response,
      synced_at    = NOW()
`

type UpsertPostInsightParams struct {
	ID              string          `json:"id"`
	PublishResultID string          `json:"publish_result_id"`
	PostID          string          `json:"post_id"`
	Platform        string          `json:"platform"`
	InsightWindow   string          `json:"insight_window"`
	Metrics         json.RawMessage `json:"metrics"`
	RawResponse     json.RawMessage `json:"raw_response"`
}

func (q *Queries) UpsertPostInsight(ctx context.Context, arg UpsertPostInsightParams) error {
	_, err := q.db.Exec(ctx, upsertPostInsight,
		arg.ID,
		arg.PublishResultID,
		arg.PostID,
		arg.Platform,
		arg.InsightWindow,
		arg.Metrics,
		arg.RawResponse,
	)
	return err
}
